version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    env_file:
      - .env.global  # Load global environment variables
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0          # MySQL image version
    container_name: mysql_db  # Name of the container
    ports:
      - "3307:3306"           # Map port 3306 of the host to port 3306 of the container
    env_file:
      - .env.global           # Load global environment variables
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"  # Absolute path to init.sql
      - db_data:/var/lib/mysql          # Volume to persist database data
    networks:
      - app_network

volumes:
  db_data:
